# Generated by Django 5.0.6 on 2024-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('nickname', models.CharField(max_length=150, unique=True, verbose_name='никнэйм')),
                ('label', models.ImageField(blank=True, null=True, upload_to='labels', verbose_name='лэйбел')),
            ],
        ),
    ]
