# Generated by Django 5.0.6 on 2024-07-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_user_options_user_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
