# Generated by Django 5.0.6 on 2024-07-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='никнэйм')),
                ('departure_date', models.DateTimeField(verbose_name='дата отправки')),
                ('at_work', models.BooleanField(default=False, verbose_name='в работе')),
                ('periodicity', models.DateTimeField(choices=[('', 'раз в день'), ('', 'раз в неделю'), ('', 'раз в месяц')], verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('title',),
            },
        ),
    ]
