# Generated by Django 5.0.6 on 2024-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.DateField(choices=[('', 'раз в день'), ('', 'раз в неделю'), ('', 'раз в месяц')], verbose_name='периодичность'),
        ),
    ]
