# Generated by Django 5.0.6 on 2024-07-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='departure_date',
            field=models.DateField(verbose_name='дата отправки'),
        ),
    ]
