# Generated by Django 5.0.6 on 2024-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='content',
            field=models.TextField(verbose_name='содержание'),
        ),
    ]
