# Generated by Django 5.0.6 on 2024-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='departure_date',
            field=models.DateTimeField(verbose_name='дата и время отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.DateField(blank=True, choices=[('', 'раз в день'), ('', 'раз в неделю'), ('', 'раз в месяц')], null=True, verbose_name='периодичность'),
        ),
    ]
