# Generated by Django 5.0.6 on 2024-08-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='periodicity',
        ),
    ]
