# Generated by Django 5.0.6 on 2024-08-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_remove_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.IntegerField(blank=True, choices=[('', 'раз в день'), ('', 'раз в неделю'), ('', 'раз в месяц')], null=True, verbose_name='периодичность'),
        ),
    ]
