# Generated by Django 5.1 on 2024-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_mailingattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='заголовок'),
        ),
    ]
